---
# Docker User
dockerUser: geoffh1977
dockerUserEmail: geoffh1977@gmail.com
license: gnu-gpl-v3.0

# Source Build Variables
buildImageName: alpine
buildImageVersion: latest

# Final Image Variables
finalImageName: kindlegen
finalImageVersion: latest
appName: KindleGen Ebook Generator
